.TH OZ-INSTALL 1 "Dec 2010" "oz-install"

.SH NAME
oz-install - tool to automatically install operating systems into files

.SH SYNOPSIS
.B oz-install [OPTIONS] <tdl-file>

.SH DESCRIPTION
This is a tool to automatically install operating system into files
that represent disk images.  The input is an XML file representing the
operating system and packages to be installed.  By default (and by
design), the first stage of the install only installs a JEOS (Just
Enough Operating System); customization, including the installation of
additional packages can also be done, but requires additional flags.

Note that oz-install does the actual installation using a combination
of KVM and libvirt, so both of these must be available (and working)
for oz-install to have a chance to succeed.

.SH OPTIONS
.TP
.B "\-c <config>"
Get the configuration from config file \fBconfig\fR, instead of the
default /etc/oz/oz.cfg.  The config file is in standard ini format
with a single section called \fBpaths\fR.  There are two possible keys
under \fBpaths\fR: \fBoutput_dir\fR describes where to store the
images after they are built, and \fBdata_dir\fR describes where to
cache install media and use temporary storage.  Both locations have to
have a decent amount of free disk space in order for oz-install to
work properly.
.TP
.B "\-d <loglevel>"
Turn on debugging output to level \fBloglevel\fR.  The log levels are:
.RS 7
.IP "0 - errors only (this is the default)"
.IP "1 - errors and warnings"
.IP "2 - errors, warnings, and information"
.IP "3 - all messages"
.IP "4 - all messages, prepended with the level and classname"
.RE
.TP
.B "\-f"
Force the download of the install media.  By default, oz-install will
always try to use a locally cached version of the install media if it
is available.  You can use this flag to force it to always download
the install media, even if it has a local version available.
.TP
.B "\-g"
Generate the CDL (a package manifest, with some additional metadata)
after the installation is complete.
.TP
.B "\-h"
Print a short help message.
.TP
.B "\-u"
Customize the image after installation.  This generally installs
additional packages onto the disk image after installation.

.SH SEE ALSO
oz-generate-cdl(1), oz-customize(1)

.SH AUTHOR
Chris Lalancette <clalance@redhat.com>
