language: python

python:
#  - "3.3"
#  - "3.2"
  - "2.7"

before_install:
  - sudo add-apt-repository -y ppa:pdffs/precise-virt
  - sudo apt-get update
  - sudo apt-get install -qq genisoimage libvirt-dev mtools openssh-client python-dev python-guestfs swig libssl1.0.0 python-m2crypto python-libvirt

# Travis uses an isolated virtualenv (see http://about.travis-ci.org/docs/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs)
# Install the system python packages to get their deps and then install the pip version to have them locally
install:
  - pip install -r requirements.txt              
  - sudo cp /usr/lib/python2.7/dist-packages/*guestfs* $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages/
  - python setup.py install
  - pip install coverage
  - pip install coveralls
  - py.test --genscript=runtests.py

env:
  - TESTFOLDER=tdl
  - TESTFOLDER=guest
  - TESTFOLDER=ozutil
  - TESTFOLDER=factory

script: 
  - coverage run -p --source=oz runtests.py --verbose --tb=short tests/$TESTFOLDER

after_success:
  - coveralls
