#!/usr/bin/python

# Copyright (C) 2010  Chris Lalancette <clalance@redhat.com>

# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation;
# version 2.1 of the License.

# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

import sys
import getopt
import os
import logging
import time

import oz.TDL
import oz.Fedora
import oz.FedoraCore
import oz.RHEL_2_1
import oz.RHEL_3
import oz.RHEL_4
import oz.RHEL_5
import oz.RHEL_6
import oz.RHL
import oz.Ubuntu
import oz.Windows
import oz.OpenSUSE
import ConfigParser

def usage():
    print "Usage: ozinstall [OPTIONS] <tdl>"
    print " OPTIONS:"
    print "  -c <config>\tGet config from <config> (default is /etc/oz/oz.cfg)"
    print "  -d <level>\tTurn up logging level.  The levels are:"
    print "\t\t\t0 - errors only (this is the default)"
    print "\t\t\t1 - errors and warnings"
    print "\t\t\t2 - errors, warnings, and information"
    print "\t\t\t3 - all messages"
    print "\t\t\t4 - all messages, prepended with the level and classname"
    print "  -f\t\tForce download of the installation media even if it is already cached"
    print "  -g\t\tGenerate the ICICLE after installation"
    print "  -h\t\tPrint this help message"
    print "  -u\t\tAfter installation, do the customization"
    print " Currently supported architectures are:"
    print "   i386, x86_64"
    print " Currently supported distros are:"
    print "   Fedora: 7, 8, 9, 10, 11, 12, 13, 14"
    print "   Fedora Core: 1, 2, 3, 4, 5, 6"
    print "   RHEL 2.1: GOLD, U2, U3, U4, U5, U6"
    print "   RHEL 3: GOLD, U1, U2, U3, U4, U5, U6, U7, U8, U9"
    print "   RHEL 4: GOLD, U1, U2, U3, U4, U5, U6, U7, U8"
    print "   RHEL 5: GOLD, U1, U2, U3, U4, U5"
    print "   RHEL 6: 0"
    print "   Ubuntu: 6.10, 7.04, 7.10, 8.04.[1,2,3,4], 8.10, 9.04, 9.10"
    print "   Windows: 2000, XP, 2003"
    print "   RHL: 7.0, 7.1, 7.2, 7.3, 8, 9"
    print "   OpenSUSE: 11.1, 11.2, 11.3"
    sys.exit(1)

try:
    opts, args = getopt.gnu_getopt(sys.argv[1:], 'c:d:fghu', ['config', 'debug', 'force-download', 'generate-icicle', 'help', 'customize'])
except getopt.GetoptError, err:
    print str(err)
    usage()

loglevel = logging.ERROR
logformat = "%(message)s"
force_download = False
config_file = "/etc/oz/oz.cfg"
generate_icicle = False
customize = False
for o, a in opts:
    if o in ("-h", "--help"):
        usage()
    elif o in ("-d", "--debug"):
        if int(a) == 0:
            loglevel = logging.ERROR
        elif int(a) == 1:
            loglevel = logging.WARNING
        elif int(a) == 2:
            loglevel = logging.INFO
        elif int(a) == 3:
            loglevel = logging.DEBUG
        elif int(a) >= 4:
            loglevel = logging.DEBUG
            logformat = logging.BASIC_FORMAT
        else:
            usage()
    elif o in ("-f", "--force-download"):
        force_download = True
    elif o in ("-g", "--generate-icicle"):
        generate_icicle = True
    elif o in ("-c", "--config"):
        config_file = a
    elif o in ("-u", "--customize"):
        customize = True
    else:
        assert False, "unhandled option"

if os.geteuid() != 0:
    print "%s must be run as root" % (sys.argv[0])
    sys.exit(2)

if len(args) != 1:
    usage()

logging.basicConfig(level=loglevel, format=logformat)

tdl = oz.TDL.TDL(args[0])

config = ConfigParser.SafeConfigParser()
if os.access(config_file, os.F_OK):
    config.read(config_file)

if tdl.distro == "Fedora":
    guest = oz.Fedora.get_class(tdl, config)
elif tdl.distro == "FedoraCore":
    guest = oz.FedoraCore.get_class(tdl, config)
elif tdl.distro == "RHEL-2.1":
    guest = oz.RHEL_2_1.get_class(tdl, config)
elif tdl.distro == "RHEL-3":
    guest = oz.RHEL_3.get_class(tdl, config)
elif tdl.distro == "RHEL-4":
    guest = oz.RHEL_4.get_class(tdl, config)
elif tdl.distro == "RHEL-5":
    guest = oz.RHEL_5.get_class(tdl, config)
elif tdl.distro == "RHEL-6":
    guest = oz.RHEL_6.get_class(tdl, config)
elif tdl.distro == "Ubuntu":
    guest = oz.Ubuntu.get_class(tdl, config)
elif tdl.distro == "Windows":
    guest = oz.Windows.get_class(tdl, config)
elif tdl.distro == "RHL":
    guest = oz.RHL.get_class(tdl, config)
elif tdl.distro == "OpenSUSE":
    guest = oz.OpenSUSE.get_class(tdl, config)
else:
    usage()

guest.cleanup_old_guest()
guest.generate_install_media(force_download)
try:
    guest.generate_diskimage()
    try:
        libvirt_xml = guest.install()

        if customize:
            guest.customize(libvirt_xml)

        if generate_icicle:
            print guest.generate_icicle(libvirt_xml)

        filename = guest.name + time.strftime("%b_%d_%Y-%H:%M:%S")
        open(filename, 'w').write(libvirt_xml)
        print "Libvirt XML was written to " + filename
    except:
        guest.cleanup_old_guest()
        raise
finally:
    guest.cleanup_install()
